//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.RTUs = new HashSet<RTU>();
        }
    
        public int LOCATION_ID { get; set; }
        public double LAT { get; set; }
        public double LNG { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual ICollection<RTU> RTUs { get; set; }
    }
}
