INSERT INTO [dbo].[LOCATION] ([LAT], [LNG],[ADDRESS]) VALUES ( 45.896 ,19.666, 'Adresa 1')
INSERT INTO [dbo].[LOCATION] ([LAT], [LNG],[ADDRESS]) VALUES ( 45.877 ,19.689, 'Adresa 2')
INSERT INTO [dbo].[LOCATION] ([LAT], [LNG],[ADDRESS]) VALUES ( 45.810 ,19.611, 'Adresa 3')
INSERT INTO [dbo].[LOCATION] ([LAT], [LNG],[ADDRESS]) VALUES ( 45.800 ,19.698, 'Adresa 4')

INSERT INTO [dbo].[RTU] ([LOCATION_ID],[NAME],[RTU_TYPE]) VALUES (1, 'rtu-1', 0)
INSERT INTO [dbo].[RTU] ([LOCATION_ID],[NAME],[RTU_TYPE]) VALUES (2, 'rtu-2', 0)
INSERT INTO [dbo].[RTU] ([LOCATION_ID],[NAME],[RTU_TYPE]) VALUES (3, 'rtu-3', 1)
INSERT INTO [dbo].[RTU] ([LOCATION_ID],[NAME],[RTU_TYPE]) VALUES (4, 'rtu-4', 1)